### ISSUE TITLE
Request > is there docker in pipeline?

### ISSUE THREAD

**Issue by egs2003** [yahesh/shared-secrets#1]
Hey, this is a great project. I would like to use it myself, find it in applications, etc. I like the lightness of the interface. But I hesitate to implement it. Have you guys thought about making it available via Docker as well? That would ensure a secure controlled implementation. At least the basic functionality.
You could then use environment variables to provide the certificates or make your own customizations if that's what you want. I already use nginxpm with letsencrypt in my environment anyway. I would not need additional certificates in it.
Just an idea, it would make me very happy. 

 

Translated with www.DeepL.com/Translator (free version)

**Comment by weizenspreu** [comment]
I'm currently in the process of containerizing the application. In that turn I'll also implement SQLite support for smaller deployments.

**Comment by weizenspreu** [comment]
I overhauled the codebase as mentioned. It now contains a Dockerfile and the README contains a description on how to build and run the application in a container.
